#version: '3'

services:
  erp:
    build: .
    env_file: .env  # Cette ligne est ajoutée pour charger les variables d'environnement
    ports:
      - "8003:8069"
    volumes:
      - ./modules:/mnt/extra-addons/
      - ./odoo_dev_conf:/etc/odoo
      - odoo-data:/var/lib/odoo
    depends_on:
      - db
      
    container_name: formation_erp

    networks:
      - erpnet

  db:
    image: postgres:15
    ports:
      - "5449:5432"
    env_file: .env
    container_name: formation_postgres
    networks:
      - erpnet

networks:
  erpnet:
    driver: bridge

volumes:
  odoo-data: